config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: {minimum: 3}
  validates :text, presence: true,
            length: {minimum: 2}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article ## auto generated during rails g model ... article:references ##
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
http_basic_authenticate_with name: "ajmaster", password: "FooBar",
                             except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def create
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
      if @article.save
        redirect_to @article
      else
        render 'new'
      end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

    def article_params
      params.require(:article).permit(:title,:text)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/index.html.erb
<h1>List of all Articles</h1>
<p>
  <%= link_to 'Create New Article', new_article_path  %>
</p>
<table>
<tr>
  <th>Title</th>
  <th>Text</th>
  <th colspan="3">Editing Options</th>
</tr>
<% @articles.each do |article| %>
<tr>
  <td> |
    <%= article.title %>
  </td>
  <td> |
    <%= truncate(article.text, length: 75) %>
  </td>
  <td> |
    <%= link_to 'Show', article_path(article) %>
  </td>
  <td> |
    <%= link_to 'Edit', edit_article_path(article) %>
  </td>
  <td> |
    <%= link_to 'Delete',
        article_path(article),
        method: :delete,
        data: {confirm: 'Are you certain?'} %>
  </td>
</tr>
<% end %>
</table>
<p>
  <%= link_to 'Home', welcome_index_path %>
</p>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= form_for :article, url: articles_path do |f| %>

<!-- Checking for Errors -->
<% if @article.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@article.errors.count, "error") %>
    prohibited this article from being saved:
  </h2>
  <p>
    <% @article.errors.full_messages.each do |msg| %>
    <ul>
      <li>
        <%= msg %>
      </li>
    </ul>
    <% end %>
  </p>
</div>
<% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<p>
  <%= link_to 'Back', articles_path %>
  | <%= link_to 'Home', welcome_index_path %>
</p>

app/views/articles/show.html.erb
<p>
  <strong>Title: </strong>
  <%= @article.title %>
</p>
<p>
  <%= @article.created_at %>
</p>
<p>
  <strong>Text: </strong>
  <%= @article.text %>
</p>
<hr>

<%= render 'comments/comment' %>

<hr>

<%= render 'comments/form' %>

<p><%= link_to 'Back', articles_path %>
   |
   <%= link_to 'Home', welcome_index_path %>
</p>

app/views/comments/_comment.html.erb
<!--  Partial for Comments -->
<!--  Partial for Comments -->
<!--  Partial for Comments -->

<h2> Comments </h2>
  <% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <%= comment.created_at %>
  </p>
  <p>
    <strong>Comment</strong>
    <%= comment.body %>
  </p>
  <p>
    <%= link_to 'Delete comment', [comment.article, comment],
        method: :Delete,
        data: {confirm: 'Are you sure?'} %>
  </p>
  <% end %>

app/views/comments/_form.html.erb
<!-- Form Partial for Comments -->
<!-- Form Partial for Comments -->
<!-- Form Partial for Comments -->

<h2> Add Comment </h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dbblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to DBBlog</h1>
<p>
  <%= link_to 'My Blog', articles_path %>
</p>